question_data = [
    {"text": "Python is a programming language.", "answer": "True"},
    {"text": "The Earth is flat.", "answer": "False"},
    {"text": "The capital of India is New Delhi.", "answer": "True"},
    {"text": "The Sun revolves around the Earth.", "answer": "False"},
    {"text": "Water boils at 100 degrees Celsius at sea level.", "answer": "True"},
    {"text": "HTML is a programming language.", "answer": "False"},
    {"text": "The Great Wall of China is visible from space with the naked eye.", "answer": "False"},
    {"text": "Python supports Object-Oriented Programming.", "answer": "True"},
    {"text": "An octopus has three hearts.", "answer": "True"},
    {"text": "Light travels faster than sound.", "answer": "True"},
    {"text": "A byte consists of 16 bits.", "answer": "False"},
    {"text": "Git is a version control system.", "answer": "True"},
    {"text": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True"},
    {"text": "Java and JavaScript are the same language.", "answer": "False"},
    {"text": "The human body has 206 bones.", "answer": "True"},
    {"text": "The chemical symbol for Gold is Ag.", "answer": "False"},
    {"text": "Mount Everest is the highest mountain above sea level.", "answer": "True"},
    {"text": "A leap year occurs every 5 years.", "answer": "False"},
    {"text": "The square root of 64 is 8.", "answer": "True"},
    {"text": "Linux is an operating system.", "answer": "True"},
]